# Generated by Django 6.0.1 on 2026-01-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_expenses_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('noCategory', 'No Category'), ('food', 'Food')], default='noCategory', max_length=10),
        ),
    ]
