# Generated by Django 6.0.2 on 2026-02-24 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_account'),
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.AddField(
            model_name='investment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.account'),
            preserve_default=False,
        ),
    ]
